/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ObjectivesIndexRouteImport } from './routes/objectives.index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as ObjectivesSlugRouteImport } from './routes/objectives.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ObjectivesIndexRoute = ObjectivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObjectivesRoute,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewRoute,
} as any)
const ObjectivesSlugRoute = ObjectivesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ObjectivesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/objectives': typeof ObjectivesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contribute'
    | '/guides'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/review'
    | '/subjects'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/review/$slug'
    | '/subjects/$slug'
    | '/objectives/'
    | '/review/'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contribute'
    | '/guides'
    | '/login'
    | '/profile'
    | '/register'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/review/$slug'
    | '/subjects/$slug'
    | '/objectives'
    | '/review'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/contribute'
    | '/guides'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/review'
    | '/subjects'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/review/$slug'
    | '/subjects/$slug'
    | '/objectives/'
    | '/review/'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ContributeRoute: typeof ContributeRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ObjectivesRoute: typeof ObjectivesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SubjectsRoute: typeof SubjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/objectives/': {
      id: '/objectives/'
      path: '/'
      fullPath: '/objectives/'
      preLoaderRoute: typeof ObjectivesIndexRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/objectives/$slug': {
      id: '/objectives/$slug'
      path: '/$slug'
      fullPath: '/objectives/$slug'
      preLoaderRoute: typeof ObjectivesSlugRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface ObjectivesRouteChildren {
  ObjectivesSlugRoute: typeof ObjectivesSlugRoute
  ObjectivesIndexRoute: typeof ObjectivesIndexRoute
}

const ObjectivesRouteChildren: ObjectivesRouteChildren = {
  ObjectivesSlugRoute: ObjectivesSlugRoute,
  ObjectivesIndexRoute: ObjectivesIndexRoute,
}

const ObjectivesRouteWithChildren = ObjectivesRoute._addFileChildren(
  ObjectivesRouteChildren,
)

interface ReviewRouteChildren {
  ReviewSlugRoute: typeof ReviewSlugRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewSlugRoute: ReviewSlugRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ContributeRoute: ContributeRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LoginRoute: LoginRoute,
  ObjectivesRoute: ObjectivesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SubjectsRoute: SubjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
